export const MainParentLayout: string = 'mx-auto max-w-7xl px-4 md:px-0 dark:bg-black'
export const MdTwoColXsOneCol: string = 'grid auto-cols-[1fr] grid-cols-[1fr] grid-rows-[auto] justify-center gap-4 gap-y-5 md:grid-cols-[1fr_1fr]'
export const MdThreeColXsOneCol: string = 'grid auto-cols-[1fr] grid-cols-[1fr] grid-rows-[auto] justify-center gap-4 gap-y-5 md:grid-cols-[1fr_1fr_1fr]'
export const MdFourColXsOneCol: string = 'grid auto-cols-[1fr] grid-cols-[1fr] grid-rows-[auto] justify-center gap-4 gap-y-5 md:grid-cols-[1fr_1fr_1fr_1fr]'
export const MdFourColXsTwoCol: string = 'grid auto-cols-[1fr] grid-cols-[1fr_1fr] grid-rows-[auto] justify-center gap-8 md:gap-4 gap-y-5 md:grid-cols-[1fr_1fr_1fr_1fr]'
export const MasonryLayout: string = 'columns-1 gap-5 sm:columns-2 sm:gap-8 md:columns-3'
export const MdTwoColXsOneColFirstHalfCol: string = 'grid auto-cols-[1fr] grid-cols-[1fr] grid-rows-[auto] justify-center gap-4 gap-y-5 md:grid-cols-[0.5fr_1fr]'
export const MdTwoColXsOneColSecondHalfCol: string = 'grid auto-cols-[1fr] grid-cols-[1fr] grid-rows-[auto] justify-center gap-4 gap-y-5 md:grid-cols-[1fr_0.3fr]'
